"Python 2.7 AMD CPU (+GL and special func)":
  script:
  - export PY_EXE=python2.7
  - export PYOPENCL_TEST=amd:pu
  - export EXTRA_INSTALL="numpy mako scipy pyfmmlib"
  - echo "CL_ENABLE_GL = True" > siteconf.py
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python2.7
  - amd-cl-cpu
  - opengl
  except:
  - tags

Python 3.5 Intel CPU:
  script:
  - export PY_EXE=python3.5
  - export PYOPENCL_TEST="intel(r):pu"
  - export EXTRA_INSTALL="numpy mako"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python3.5
  - intel-cl-cpu
  except:
  - tags
Python 3.5 AMD CPU:
  script:
  - export PY_EXE=python3.5
  - export PYOPENCL_TEST=amd:pu
  - export EXTRA_INSTALL="numpy mako"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python3.5
  - amd-cl-cpu
  except:
  - tags
Python 2.6 AMD CPU:
  script:
  - export PY_EXE=python2.6
  - export PYOPENCL_TEST=amd:pu
  - export EXTRA_INSTALL="numpy mako"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python2.6
  - amd-cl-cpu
  except:
  - tags

Python 3.5 Titan X:
  script:
  - export PY_EXE=python3.5
  - export PYOPENCL_TEST=nvi:titan
  - export EXTRA_INSTALL="numpy mako"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python3.5
  - nvidia-titan-x
  except:
  - tags

Python 3.5 K40:
  script:
  - export PY_EXE=python3.5
  - export PYOPENCL_TEST=nvi:k40
  - export EXTRA_INSTALL="numpy mako"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python3.5
  - nvidia-k40
  except:
  - tags

Python 3.5 AMD GPU:
  script:
  - export PY_EXE=python3.5
  - export PYOPENCL_TEST=amd:fiji
  - export EXTRA_INSTALL="numpy mako"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python3.5
  - amd-fiji
  except:
  - tags

Python 3.5 POCL CL 1.1:
  script:
  - export PY_EXE=python3.5
  - export PYOPENCL_TEST=portable
  - export EXTRA_INSTALL="numpy mako"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - echo "CL_PRETEND_VERSION = '1.1'" > siteconf.py
  - ". ./build-and-test-py-project.sh"
  tags:
  - python3.5
  - pocl
  except:
  - tags

Python 2.7 POCL:
  script:
  - export PY_EXE=python2.7
  - export PYOPENCL_TEST=portable
  - export EXTRA_INSTALL="numpy mako"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python2.7
  - pocl
  except:
  - tags

Python 2.7 Apple:
  script:
  - export PY_EXE=python2.7
  - export PYOPENCL_TEST=app:cpu
  - export EXTRA_INSTALL="numpy mako"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python2.7
  - apple
  except:
  - tags

PyPy POCL:
  script:
  - export PY_EXE=pypy
  - export PYOPENCL_TEST=portable
  - export EXTRA_INSTALL="numpy mako"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - pypy
  - pocl
  except:
  - tags

Documentation:
  script:
  - EXTRA_INSTALL="numpy mako"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-docs.sh
  - ". ./build-docs.sh"
  tags:
  - python3.5
  only:
  - master

Flake8:
  script:
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/prepare-and-run-flake8.sh
  - ". ./prepare-and-run-flake8.sh pyopencl test"
  tags:
  - python3.5
  except:
  - tags
